name: Scigility
channels:
  - conda-forge
dependencies:
  - pyspark=3.5.* # compiled for Java 17
  - pandas
  - pyarrow
  - openjdk=17 # Spark/Hadoop compatible LTS version
  - s3fs
  - pyyaml
  - pytest
  - python-dotenv
