# File reading and writing configuration
# We are reading the csv files from S3 bucket but writing the parquet files to a local directory
s3:
  bucket: "${AWS_BUCKET_NAME}"
  input_prefix: ""
  output:
    transactions: "processed/cleaned-trans"
    loans: "processed/avg-loans"

# Cleaning rules
cleaning:
  trans_type_corrections:
    PRJIEM: PRIJEM
