name: CI

on:
  push:
    branches: ["main"]
  pull_request:

# Global environment variables reused in jobs
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/bank_pipeline

jobs:
  tests:
    name: "Run Unit Tests"
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Micromamba provides fast conda environments with caching
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: Scigility
          cache-downloads: true
          cache-env: true

      - name: Run pytest & generate coverage
        shell: bash -l {0}
        run: |
          pytest -q --cov=src --cov-report=xml

  build-and-push:
    name: "Build & Push Docker Image"
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
